name: Deploy
on:
  workflow_dispatch:

jobs:
    windows:
        runs-on: windows-2019
        steps:
            - uses: actions/checkout@v1
              with:
                fetch-depth: 1
            
            - name: make dirs
              run: |
                mkdir plugins
                mkdir projects\3rdparty
                mkdir projects\itch_io
                mkdir external\physx\lib\vs2017\win64\release_static
                
            - name: fetch procedural geometry plugin
              working-directory: plugins
              run: |
                git.exe clone https://github.com/nem0/lumixengine_procedural_geom.git procedural_geom
            
            - name: fetch shader_editor plugin
              working-directory: plugins
              run: |
                git.exe clone https://github.com/nem0/lumixengine_shader_editor.git shader_editor
            
            - name: fetch maps plugin
              working-directory: plugins
              run: |
                git.exe clone https://github.com/nem0/lumixengine_maps.git maps
            
            - name: fetch dx plugin
              working-directory: plugins
              run: |
                git.exe clone https://github.com/nem0/lumixengine_dx.git dx
            
            - name: fetch marketplace plugin
              working-directory: plugins
              run: |
                git.exe clone https://github.com/nem0/lumixengine_market.git market
            
            - name: download physx
              working-directory: projects\3rdparty
              run: |
                git.exe clone --depth=1 https://github.com/nem0/PhysX.git physx
            
            - name: create physx solution
              working-directory: projects\3rdparty\PhysX\physx
              run: |
                ./generate_projects.bat lumix_vc17win64_static
            
            - name: build physx
              working-directory: projects\3rdparty\PhysX\physx
              shell: cmd
              run: |
                "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/MSBuild/Current/Bin/MSBuild.exe" compiler\vc17win64\PhysXSDK.sln /p:Configuration=Release /p:Platform=x64
                
            - name: deploy physx
              working-directory: projects
              run: |
                copy 3rdparty\PhysX\physx\bin\win.x86_64.vc141.md\release\PhysXCharacterKinematic_static_64.lib ..\external\physx\lib\vs2017\win64\release_static\
                copy 3rdparty\PhysX\physx\bin\win.x86_64.vc141.md\release\PhysXCommon_static_64.lib			   ..\external\physx\lib\vs2017\win64\release_static\
                copy 3rdparty\PhysX\physx\bin\win.x86_64.vc141.md\release\PhysXCooking_static_64.lib			   ..\external\physx\lib\vs2017\win64\release_static\
                copy 3rdparty\PhysX\physx\bin\win.x86_64.vc141.md\release\PhysXExtensions_static_64.lib		   ..\external\physx\lib\vs2017\win64\release_static\
                copy 3rdparty\PhysX\physx\bin\win.x86_64.vc141.md\release\PhysXFoundation_static_64.lib		   ..\external\physx\lib\vs2017\win64\release_static\
                copy 3rdparty\PhysX\physx\bin\win.x86_64.vc141.md\release\PhysXPvdSDK_static_64.lib			   ..\external\physx\lib\vs2017\win64\release_static\
                copy 3rdparty\PhysX\physx\bin\win.x86_64.vc141.md\release\PhysXVehicle_static_64.lib			   ..\external\physx\lib\vs2017\win64\release_static\
                copy 3rdparty\PhysX\physx\bin\win.x86_64.vc141.md\release\PhysX_static_64.lib				   ..\external\physx\lib\vs2017\win64\release_static\
            
            - name: make dx11 project
              working-directory: projects
              run: |
                ./genie.exe --with-app --static-physx vs2019
                
            - name: get butler
              working-directory: projects
              run: |
                curl -L -o butler.zip https://broth.itch.ovh/butler/windows-amd64/LATEST/archive/default
                7z x butler.zip

            - name: build dx11 engine
              working-directory: projects
              shell: cmd
              run: |
                "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/MSBuild/Current/Bin/MSBuild.exe" tmp/vs2019/LumixEngine.sln /p:Configuration=RelWithDebInfo

            - name: Publish DX11 version
              working-directory: projects
              run: |
                copy tmp\vs2019\bin\RelWithDebInfo\studio.exe itch_io\
                copy tmp\vs2019\bin\RelWithDebInfo\app.exe itch_io\
                copy .itch.toml itch_io\
                xcopy /E /Y ..\data itch_io
                ./butler.exe push itch_io mikulasflorek/lumix-engine:win-64-dx                
              env:
                BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}

            - uses: actions/upload-artifact@v3
              with:
                name: itch-io-dx
                path: projects/itch_io

            - name: make gl project with plugins
              working-directory: projects
              run: |
                ./genie.exe --static-physx --nodx --with-app vs2019
                
            - name: build gl engine
              working-directory: projects
              shell: cmd
              run: |
                "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/MSBuild/Current/Bin/MSBuild.exe" tmp/vs2019/LumixEngine.sln /p:Configuration=RelWithDebInfo
            
            - name: Publish GL version
              working-directory: projects
              run: |
                copy tmp\vs2019\bin\RelWithDebInfo\studio.exe itch_io\
                copy tmp\vs2019\bin\RelWithDebInfo\app.exe itch_io\
                ./butler.exe push itch_io mikulasflorek/lumix-engine:win-64-gl                
              env:
                BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
